const riddles = [ 

    { riddle: "What has to be broken before you can use it?", answer: "egg" },
    { riddle: "I’m tall when I’m young, and I’m short when I’m old. What am I?", answer: "candle" },
    { riddle: "What is full of holes but still holds water?", answer: "sponge" },
    { riddle: "What is always in front of you but can’t be seen?", answer: "future" },
    { riddle: "What can you break, even if you never pick it up or touch it?", answer: "promise" },
    { riddle: "What goes up but never comes down?", answer: "age" },
    { riddle: "What gets wet while drying?", answer: "towel" },
    { riddle: "What can’t talk but will reply when spoken to?", answer: "echo" },
    { riddle: "I have branches, but no fruit, trunk or leaves. What am I?", answer: "bank" },
    { riddle: "The more of this there is, the less you see. What is it?", answer: "darkness" },
    { riddle: "I follow you all the time and copy your every move, but you can’t touch me or catch me. What am I?", answer: "shadow"},
    { riddle: "What has many keys but can’t open a single lock?", answer: "piano"},
    { riddle: "What is black when it’s clean and white when it’s dirty?", answer: "chalkboard"},
    { riddle: "What gets bigger when more is taken away?", answer: "hole"},
    { riddle: "I’m light as a feather, yet the strongest person can’t hold me for five minutes. What am I?", answer: "breath"},
    { riddle: "I’m found in socks, scarves and mittens; and often in the paws of playful kittens. What am I?", answer: "yarn"},
    { riddle: "Where does today come before yesterday?", answer: "dictionary"},
    { riddle: "What invention lets you look right through a wall?", answer: "window"},
    { riddle: "If you’ve got me, you want to share me; if you share me, you haven’t kept me. What am I?", answer: "secret"},
    { riddle: "If you’re running in a race and you pass the person in second place, what place are you in?", answer: "second"},
    { riddle: "It belongs to you, but other people use it more than you do. What is it?", answer: "name"},
    { riddle: "What has one eye, but can’t see?", answer: "needle"},
    { riddle: "What has hands, but can’t clap?", answer: "clock"},
    { riddle: "What has legs, but doesn’t walk?", answer: "table"},
    { riddle: "What can you catch, but not throw?", answer: "cold"},
    { riddle: "What has many teeth, but can’t bite?", answer: "comb"},
    { riddle: "What runs all around a backyard, yet never moves?", answer: "fence"},
    { riddle: "What has a thumb and four fingers, but is not a hand?", answer: "glove"},
    { riddle: "What has a head and a tail but no body?", answer: "coin"},
    { riddle: "What building has the most stories?", answer: "library"},
    { riddle: "I am an odd number. Take away a letter and I become even. What number am I?", answer: "seven"},
    { riddle: "What five-letter word becomes shorter when you add two letters to it?", answer: "short"},
    { riddle: 'What begins with an "e" and only contains one letter?', answer: "envelope"},
    { riddle: "A word I know, six letters it contains, remove one letter and 12 remains. What is it?", answer: "dozen"},
    { riddle: "You see me once in June, twice in November and not at all in May. What am I?", answer2: "e"},
    { riddle: "Two in a corner, one in a room, zero in a house, but one in a shelter. What is it?", answer2: "r"},
    { riddle: "I am the beginning of everything, the end of everywhere. I'm the beginning of eternity, the end of time and space. What am I?", answer2: "e"},
    { riddle: "What 4-letter word can be written forward, backward or upside down, and can still be read from left to right?", answer: "noon"},
    { riddle: "I am a word of letters three; add two and fewer there will be. What word am I?", answer: "few"},
    { riddle: "What word of five letters has one left when two are removed?", answer: "stone"},
    { riddle: "What is the end of everything?", answer2: "g"},
    { riddle: "What word is pronounced the same if you take away four of its five letters?", answer: "queue"},
    { riddle: "What word in the English language does the following: The first two letters signify a male, the first three letters signify a female, the first four letters signify a great, while the entire world signifies a great woman. What is the word?", answer: "heroine"},
    { riddle: "What is so fragile that saying its name breaks it?", answer: "silence"},
    { riddle: "What can run but never walks, has a mouth but never talks, has a head but never weeps, has a bed but never sleeps?", answer: "river"},
    { riddle: "What can fill a room but takes up no space?", answer: "light"},
    { riddle: "If you drop me I’m sure to crack, but give me a smile and I’ll always smile back. What am I?", answer: "mirror"},
    { riddle: "The more you take, the more you leave behind. What are they?", answer: "footstep"},
    { riddle: "I turn once, what is out will not get in. I turn again, what is in will not get out. What am I?", answer: "key"},
    { riddle: "People make me, save me, change me, raise me. What am I?", answer: "money"},
    { riddle: "What goes through cities and fields, but never moves?", answer: "road"},
    { riddle: "I am always hungry and will die if not fed, but whatever I touch will soon turn red. What am I?", answer: "fire"},
    { riddle: "The person who makes it has no need of it; the person who buys it has no use for it. The person who uses it can neither see nor feel it. What is it?", answer: "coffin"},
    { riddle: "With pointed fangs I sit and wait; with piercing force I crunch out fate; grabbing victims, proclaiming might; physically joining with a single bite. What am I?", answer: "stapler"},
    { riddle: "I have lakes with no water, mountains with no stone and cities with no buildings. What am I?", answer: "map"},
    { riddle: "What does man love more than life, hate more than death or mortal strife; that which contented men desire; the poor have, the rich require; the miser spends, the spendthrift saves, and all men carry to their graves?", answer: "nothing"},
    { riddle: "Poor people have it. Rich people need it. If you eat it you die. What is it?", answer: "nothing"},
    { riddle: "What kind of tree can you carry in your hand?", answer: "palm"},
    { riddle: "They come out at night without being called, and are lost in the day without being stolen. What are they?", answer: "star"},
    { riddle: "I can be cracked, made, told, and played. What am I?", answer: "joke"},
    { riddle: "I love to dance, and twist. I shake my tail as I sail away. When I fly wingless into the sky. What am I?", answer: "kite"},
];