const riddles = [ 

    { riddle: "What has to be broken before you can use it?", answer: "egg" },
    { riddle: "I’m tall when I’m young, and I’m short when I’m old. What am I?", answer: "candle" },
    { riddle: "What is full of holes but still holds water?", answer: "sponge" },
    { riddle: "What is always in front of you but can’t be seen?", answer: "future" },
    { riddle: "What can you break, even if you never pick it up or touch it?", answer: "promise" },
    { riddle: "What goes up but never comes down?", answer: "age" },
    { riddle: "What gets wet while drying?", answer: "towel" },
    { riddle: "What can’t talk but will reply when spoken to?", answer: "echo" },
    { riddle: "I have branches, but no fruit, trunk or leaves. What am I?", answer: "bank" },
    { riddle: "The more of this there is, the less you see. What is it?", answer: "darkness" },
    // { riddle: "What month of the year has 28 days?", answer: "all", answer2: "every" },
    // { riddle: "What can you keep after giving to someone?", answer: "word", answer2: "word" },
    { riddle: "I follow you all the time and copy your every move, but you can’t touch me or catch me. What am I?", answer: "shadow"},
    { riddle: "What has many keys but can’t open a single lock?", answer: "piano"},
    { riddle: "What is black when it’s clean and white when it’s dirty?", answer: "chalkboard"},
    { riddle: "What gets bigger when more is taken away?", answer: "hole"},
    { riddle: "I’m light as a feather, yet the strongest person can’t hold me for five minutes. What am I?", answer: "breath"},
    { riddle: "I’m found in socks, scarves and mittens; and often in the paws of playful kittens. What am I?", answer: "yarn"},
    { riddle: "Where does today come before yesterday?", answer: "dictionary"},
    { riddle: "What invention lets you look right through a wall?", answer: "window"},
    { riddle: "If you’ve got me, you want to share me; if you share me, you haven’t kept me. What am I?", answer: "secret"},
    { riddle: "If you’re running in a race and you pass the person in second place, what place are you in?", answer: "second"},
    { riddle: "It belongs to you, but other people use it more than you do. What is it?", answer: "name"},
    { riddle: "What has one eye, but can’t see?", answer: "needle"},
    { riddle: "What has hands, but can’t clap?", answer: "clock"},
    { riddle: "What has legs, but doesn’t walk?", answer: "table"},
    { riddle: "What can you catch, but not throw?", answer: "cold"},
    { riddle: "What has many teeth, but can’t bite?", answer: "comb"},
    { riddle: "What runs all around a backyard, yet never moves?", answer: "fence"},
    { riddle: "What has a thumb and four fingers, but is not a hand?", answer: "glove"},
    { riddle: "What has a head and a tail but no body?", answer: "coin"},
    { riddle: "What building has the most stories?", answer: "library"},
    { riddle: "I am an odd number. Take away a letter and I become even. What number am I?", answer: "seven"},
    { riddle: "What five-letter word becomes shorter when you add two letters to it?", answer: "short"},
];